### ISSUE TITLE
Do the trigonometric builtins use angles in radians?

### ISSUE THREAD

**Issue by tinyplasticgreyknight** [tinyplasticgreyknight/modern-docs#4]

**Comment by IreneKnapp** [comment]
Yes, radians.  Like all of the math subtleties where there's more than one implementation choice, this is matching the behavior of the standard C library, but I don't want to include that standard as a normative reference, so just say the behavior explicitly.

**Comment by tinyplasticgreyknight** [comment]
Updated text accordingly.
